"""re-add security columns dropped by 2802eb62c668

Revision ID: c4d5e6f7a8b9
Revises: 9e8e44b24073
Create Date: 2026-09-04

2802eb62c668 (autogenerated) dropped the columns added by
add_security_columns_20260902, but services/ticket_verification.py and
services/job_queue.py still require them. Re-add idempotently.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c4d5e6f7a8b9"
down_revision: Union[str, None] = "9e8e44b24073"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table: str, column: str) -> bool:
    bind = op.get_bind()
    insp = sa.inspect(bind)
    return any(c["name"] == column for c in insp.get_columns(table))


def upgrade() -> None:
    if not _has_column("ticket_verification", "resend_count"):
        op.add_column(
            "ticket_verification",
            sa.Column("resend_count", sa.Integer(), nullable=False, server_default="0"),
        )
    if not _has_column("ticket_verification", "send_attempts"):
        op.add_column(
            "ticket_verification",
            sa.Column("send_attempts", sa.Integer(), nullable=False, server_default="1"),
        )
    if not _has_column("ticket_verification", "last_sent_at"):
        op.add_column(
            "ticket_verification",
            sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        )
    if not _has_column("ticket_verification", "verified_at"):
        op.add_column(
            "ticket_verification",
            sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        )
    if not _has_column("knowledge_injection_job", "attempts"):
        op.add_column(
            "knowledge_injection_job",
            sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        )


def downgrade() -> None:
    if _has_column("knowledge_injection_job", "attempts"):
        op.drop_column("knowledge_injection_job", "attempts")
    if _has_column("ticket_verification", "verified_at"):
        op.drop_column("ticket_verification", "verified_at")
    if _has_column("ticket_verification", "last_sent_at"):
        op.drop_column("ticket_verification", "last_sent_at")
    if _has_column("ticket_verification", "send_attempts"):
        op.drop_column("ticket_verification", "send_attempts")
    if _has_column("ticket_verification", "resend_count"):
        op.drop_column("ticket_verification", "resend_count")
